'use client';

import { motion, useInView } from 'framer-motion';
import Link from 'next/link';
import { useRef } from 'react';
import {
  Zap, TrendingUp, Shield, BarChart3, CheckCircle,
  ArrowRight, Star, Globe, ChevronRight
} from 'lucide-react';

const fadeUp = (d = 0) => ({
  initial: { opacity: 0, y: 28 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true },
  transition: { duration: 0.55, delay: d, ease: [0.22, 1, 0.36, 1] as any },
});

const features = [
  { icon: Zap,       title: 'Instant Audit',       desc: 'Full CRO analysis in under 30 seconds. Thumb-zone, CTA, page speed, social proof — all scored.' },
  { icon: TrendingUp, title: 'Revenue Recovery',   desc: "We calculate the exact dollar amount you're losing and show you precisely how to get it back." },
  { icon: Shield,    title: 'AI-Powered Fixes',    desc: 'One-click fixes generated by our AI. Applied directly to your Shopify theme — no developer needed.' },
  { icon: BarChart3, title: 'Trend Tracking',      desc: 'Track your revenue score over time and see the compound effect of every fix you apply.' },
];

const testimonials = [
  { name: 'James Morrison', role: 'Founder, ModernThread', quote: 'Found $8,400/mo in leaks on our first audit. The ROI was immediate.', rating: 5 },
  { name: 'Sarah Chen',     role: 'Head of Growth, Velour', quote: 'Finally a tool that speaks in dollar amounts, not percentages. This changed everything.', rating: 5 },
  { name: 'Mark Okafor',    role: 'DTC Operator',           quote: 'I was skeptical but the CTA position fix alone lifted our CVR by 18%.', rating: 5 },
];

const pricingTiers = [
  { name: 'Starter', price: 49,  highlight: false, feature: '10 audits/month' },
  { name: 'Growth',  price: 149, highlight: true,  feature: '50 audits + AI fixes' },
  { name: 'Scale',   price: 399, highlight: false, feature: 'Unlimited everything' },
];

export default function HomePage() {
  return (
    <div className="min-h-screen bg-[#F8FAFC] font-body">
      {/* ── NAV ──────────────────────────────────────────── */}
      <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur border-b border-slate-200/80">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-[#10374E] flex items-center justify-center">
              <Zap size={14} className="text-[#53F6FF]" />
            </div>
            <span className="font-display font-bold text-[#10374E] text-lg">RevenueArchitect</span>
          </div>
          <div className="hidden md:flex items-center gap-6 text-sm text-slate-600">
            <a href="#features" className="hover:text-slate-900 transition-colors">Features</a>
            <a href="#pricing"  className="hover:text-slate-900 transition-colors">Pricing</a>
            <a href="#social"   className="hover:text-slate-900 transition-colors">Testimonials</a>
          </div>
          <div className="flex items-center gap-3">
            <Link href="/sign-in"  className="text-sm text-slate-600 hover:text-slate-900 px-3 py-2 transition-colors">Sign in</Link>
            <Link href="/sign-up"  className="text-sm font-semibold px-4 py-2 rounded-xl bg-[#10374E] text-white hover:bg-[#0d2e42] transition-colors flex items-center gap-1.5">
              Start free <ArrowRight size={13} />
            </Link>
          </div>
        </div>
      </nav>

      {/* ── HERO ─────────────────────────────────────────── */}
      <section className="relative overflow-hidden pt-24 pb-20 px-6">
        {/* Background glow */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[600px] bg-[#53F6FF]/6 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute top-20 right-0 w-[400px] h-[400px] bg-[#093090]/5 rounded-full blur-3xl pointer-events-none" />

        <div className="max-w-5xl mx-auto text-center relative">
          <motion.div {...fadeUp(0)} className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[#10374E]/8 border border-[#10374E]/12 text-[#10374E] text-xs font-semibold mb-6">
            <span className="w-1.5 h-1.5 rounded-full bg-[#53F6FF] animate-pulse" />
            AI-Powered Shopify Revenue Intelligence
          </motion.div>

          <motion.h1 {...fadeUp(0.08)} className="text-5xl md:text-7xl font-bold font-display text-slate-900 leading-[1.08] mb-6">
            Stop losing money<br />
            <span className="gradient-text">your store is leaking.</span>
          </motion.h1>

          <motion.p {...fadeUp(0.15)} className="text-xl text-slate-500 max-w-2xl mx-auto mb-10 leading-relaxed">
            RevenueArchitect audits your Shopify store in 30 seconds, identifies every conversion leak in dollar terms, and generates one-click fixes — no developer needed.
          </motion.p>

          <motion.div {...fadeUp(0.22)} className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link
              href="/sign-up"
              className="flex items-center gap-2 px-7 py-4 rounded-2xl bg-[#10374E] text-white font-semibold text-base hover:bg-[#0d2e42] transition-all shadow-lg shadow-[#10374E]/20 hover:shadow-xl hover:shadow-[#10374E]/25 hover:-translate-y-0.5"
            >
              <Zap size={18} className="text-[#53F6FF]" /> Start your free audit
            </Link>
            <Link
              href="/sign-in"
              className="flex items-center gap-2 px-7 py-4 rounded-2xl border border-slate-200 bg-white text-slate-700 font-medium text-base hover:border-slate-300 transition-all"
            >
              Sign in <ChevronRight size={16} />
            </Link>
          </motion.div>

          {/* Social proof bar */}
          <motion.div {...fadeUp(0.3)} className="mt-14 flex flex-wrap items-center justify-center gap-6 text-sm text-slate-500">
            <span className="flex items-center gap-1.5"><CheckCircle size={14} className="text-emerald-500" /> No credit card required</span>
            <span className="flex items-center gap-1.5"><CheckCircle size={14} className="text-emerald-500" /> Results in &lt; 30 seconds</span>
            <span className="flex items-center gap-1.5"><CheckCircle size={14} className="text-emerald-500" /> Cancel anytime</span>
          </motion.div>
        </div>

        {/* Dashboard preview card */}
        <motion.div
          initial={{ opacity: 0, y: 60, scale: 0.97 }}
          whileInView={{ opacity: 1, y: 0, scale: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7, delay: 0.35, ease: [0.22, 1, 0.36, 1] as any }}
          className="max-w-4xl mx-auto mt-16 rounded-2xl border border-slate-200 bg-white shadow-2xl shadow-slate-900/8 overflow-hidden"
        >
          {/* Fake browser bar */}
          <div className="flex items-center gap-2 px-4 py-3 bg-slate-50 border-b border-slate-200">
            <div className="w-3 h-3 rounded-full bg-red-300" />
            <div className="w-3 h-3 rounded-full bg-yellow-300" />
            <div className="w-3 h-3 rounded-full bg-green-300" />
            <div className="flex-1 mx-4 h-6 rounded-md bg-slate-200/80 flex items-center px-3">
              <span className="text-xs text-slate-400">app.revenuearchitect.ai/dashboard</span>
            </div>
          </div>

          {/* Fake dashboard */}
          <div className="flex h-64 bg-[#F8FAFC]">
            {/* Sidebar */}
            <div className="w-48 navy-gradient p-4 space-y-2">
              {['Dashboard', 'New Audit', 'History', 'Billing'].map((item, i) => (
                <div key={item} className={`h-7 rounded-lg flex items-center px-3 ${i === 0 ? 'bg-[#53F6FF]/15' : 'bg-white/5'}`}>
                  <div className="w-3 h-3 rounded bg-white/20 mr-2" />
                  <div className={`h-2 rounded ${i === 0 ? 'bg-[#53F6FF]/60 w-16' : 'bg-white/20 w-14'}`} />
                </div>
              ))}
            </div>

            {/* Content */}
            <div className="flex-1 p-5 space-y-4">
              <div className="grid grid-cols-4 gap-3">
                {[['$24,800', 'Recovered'], ['14', 'Leaks'], ['38', 'Audits'], ['94%', 'Fix Rate']].map(([v, l]) => (
                  <div key={l} className="bg-white rounded-xl border border-slate-200 p-3">
                    <div className="text-lg font-bold text-[#10374E]">{v}</div>
                    <div className="h-1.5 w-12 bg-slate-100 rounded mt-1.5" />
                  </div>
                ))}
              </div>
              <div className="bg-white rounded-xl border border-slate-200 p-4 flex items-end gap-1 h-28">
                {[40, 55, 48, 70, 65, 80, 90].map((h, i) => (
                  <div key={i} className="flex-1 rounded-sm" style={{ height: `${h}%`, background: `rgba(83,246,255,${0.3 + i * 0.1})` }} />
                ))}
              </div>
            </div>
          </div>
        </motion.div>
      </section>

      {/* ── STATS BAR ────────────────────────────────────── */}
      <section className="navy-gradient py-12 px-6">
        <div className="max-w-4xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8">
          {[
            { val: '$2.4M+', label: 'Revenue Recovered' },
            { val: '1,200+', label: 'Audits Run' },
            { val: '94%',    label: 'Fix Success Rate' },
            { val: '< 30s',  label: 'Audit Speed' },
          ].map((s, i) => (
            <motion.div key={s.label} {...fadeUp(i * 0.07)} className="text-center">
              <p className="text-3xl font-bold text-[#53F6FF] font-display">{s.val}</p>
              <p className="text-white/60 text-sm mt-1">{s.label}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── FEATURES ─────────────────────────────────────── */}
      <section id="features" className="py-24 px-6">
        <div className="max-w-5xl mx-auto">
          <motion.div {...fadeUp(0)} className="text-center mb-16">
            <h2 className="text-4xl font-bold font-display text-slate-900 mb-4">Everything you need to plug the leaks</h2>
            <p className="text-slate-500 max-w-xl mx-auto">One platform to find, understand, and fix every conversion bottleneck in your Shopify store.</p>
          </motion.div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {features.map((f, i) => (
              <motion.div key={f.title} {...fadeUp(0.08 * i)} className="bg-white rounded-2xl border border-slate-200/80 p-7 hover:shadow-md transition-shadow group">
                <div className="w-12 h-12 rounded-2xl bg-[#10374E]/8 flex items-center justify-center mb-5 group-hover:bg-[#10374E]/12 transition-colors">
                  <f.icon size={22} className="text-[#10374E]" />
                </div>
                <h3 className="font-bold text-slate-900 mb-2 text-lg">{f.title}</h3>
                <p className="text-slate-500 text-sm leading-relaxed">{f.desc}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── TESTIMONIALS ─────────────────────────────────── */}
      <section id="social" className="py-24 px-6 bg-white">
        <div className="max-w-5xl mx-auto">
          <motion.div {...fadeUp(0)} className="text-center mb-14">
            <h2 className="text-4xl font-bold font-display text-slate-900 mb-4">Trusted by revenue-obsessed teams</h2>
          </motion.div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {testimonials.map((t, i) => (
              <motion.div key={t.name} {...fadeUp(0.08 * i)} className="bg-[#F8FAFC] rounded-2xl border border-slate-200/80 p-6">
                <div className="flex gap-0.5 mb-4">
                  {Array.from({ length: t.rating }).map((_, j) => (
                    <Star key={j} size={14} className="fill-[#DB7245] text-[#DB7245]" />
                  ))}
                </div>
                <blockquote className="text-slate-700 text-sm leading-relaxed mb-5">"{t.quote}"</blockquote>
                <div>
                  <p className="font-semibold text-slate-900 text-sm">{t.name}</p>
                  <p className="text-xs text-slate-500 mt-0.5">{t.role}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── PRICING ──────────────────────────────────────── */}
      <section id="pricing" className="py-24 px-6">
        <div className="max-w-4xl mx-auto">
          <motion.div {...fadeUp(0)} className="text-center mb-14">
            <h2 className="text-4xl font-bold font-display text-slate-900 mb-4">Simple, ROI-driven pricing</h2>
            <p className="text-slate-500">You&apos;ll typically recover the plan cost within your first audit.</p>
          </motion.div>

          <div className="grid grid-cols-3 gap-4">
            {pricingTiers.map((tier, i) => (
              <motion.div
                key={tier.name} {...fadeUp(0.08 * i)}
                className={`rounded-2xl p-6 border ${tier.highlight ? 'navy-gradient border-transparent' : 'bg-white border-slate-200'}`}
              >
                <h3 className={`font-bold text-lg font-display mb-1 ${tier.highlight ? 'text-white' : 'text-slate-900'}`}>{tier.name}</h3>
                <div className="flex items-end gap-1 mb-4">
                  <span className={`text-3xl font-bold ${tier.highlight ? 'text-[#53F6FF]' : 'text-slate-900'}`}>${tier.price}</span>
                  <span className={`text-sm mb-1 ${tier.highlight ? 'text-white/60' : 'text-slate-500'}`}>/mo</span>
                </div>
                <p className={`text-sm mb-6 ${tier.highlight ? 'text-white/70' : 'text-slate-600'}`}>{tier.feature}</p>
                <Link
                  href="/sign-up"
                  className={`block text-center py-2.5 rounded-xl text-sm font-semibold transition-colors ${
                    tier.highlight
                      ? 'bg-[#53F6FF] text-[#10374E] hover:bg-white'
                      : 'border border-slate-200 text-slate-700 hover:bg-slate-50'
                  }`}
                >
                  Get started
                </Link>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA BANNER ───────────────────────────────────── */}
      <section className="py-20 px-6">
        <motion.div {...fadeUp(0)} className="max-w-3xl mx-auto navy-gradient rounded-3xl p-12 text-center relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-[#53F6FF]/8 rounded-full blur-3xl pointer-events-none" />
          <h2 className="text-4xl font-bold font-display text-white mb-4">Start recovering revenue today.</h2>
          <p className="text-white/60 mb-8 text-lg">Your first audit is free. No card needed.</p>
          <Link
            href="/sign-up"
            className="inline-flex items-center gap-2 px-8 py-4 bg-[#53F6FF] text-[#10374E] font-bold rounded-2xl hover:bg-white transition-colors text-base shadow-lg shadow-[#53F6FF]/20"
          >
            <Zap size={18} /> Run your free audit
          </Link>
        </motion.div>
      </section>

      {/* ── FOOTER ───────────────────────────────────────── */}
      <footer className="border-t border-slate-200 py-8 px-6 bg-white">
        <div className="max-w-5xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg bg-[#10374E] flex items-center justify-center">
              <Zap size={12} className="text-[#53F6FF]" />
            </div>
            <span className="font-display font-bold text-[#10374E] text-sm">RevenueArchitect AI</span>
          </div>
          <p className="text-xs text-slate-400">© 2026 RevenueArchitect AI. All rights reserved.</p>
          <div className="flex gap-5 text-xs text-slate-400">
            <a href="#" className="hover:text-slate-600 transition-colors">Privacy</a>
            <a href="#" className="hover:text-slate-600 transition-colors">Terms</a>
            <a href="#" className="hover:text-slate-600 transition-colors">Contact</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
